# Generated by Django 3.2.9 on 2022-02-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(default='', max_length=11, unique=True, verbose_name='Телефон'),
        ),
    ]
